# Generated by Django 2.0.7 on 2020-03-24 14:13

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DeliveryPeriod',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('starting_date', models.DateTimeField(auto_now_add=True)),
                ('ending_date', models.DateTimeField()),
                ('gct', models.PositiveIntegerField()),
                ('duration', models.PositiveIntegerField()),
                ('status', models.CharField(choices=[('started', 'STARTED'), ('gct', 'GCT'), ('ended', 'ENDED')], default='started', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='FlexibilityServiceProvider',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eic_code', models.TextField()),
                ('identification', models.TextField(unique=True)),
                ('baseline_scenario', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eic_code', models.TextField()),
                ('product_name', models.TextField()),
                ('price_conditions', models.DecimalField(decimal_places=3, max_digits=10, validators=[django.core.validators.MinValueValidator(0.01), django.core.validators.MaxValueValidator(5000)])),
                ('resolution', models.DecimalField(decimal_places=3, max_digits=10, validators=[django.core.validators.MinValueValidator(0.01)])),
                ('divisibility', models.BooleanField()),
                ('ramping_period', models.PositiveIntegerField()),
                ('delivery_period', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(60)])),
                ('validity', models.PositiveIntegerField()),
                ('pricing_method', models.TextField()),
                ('gate_closure_time', models.PositiveIntegerField()),
                ('validated_by_fpo', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='SecondarySystemOperator',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='SystemOperator',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eic_code', models.TextField()),
                ('identification', models.TextField(unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name='secondarysystemoperator',
            name='is_secondary_of_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='is_secondary_of_id', to='flexibility_platform.SystemOperator'),
        ),
        migrations.AddField(
            model_name='secondarysystemoperator',
            name='original',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='original_id', to='flexibility_platform.SystemOperator'),
        ),
    ]
