# Generated by Django 2.0.7 on 2020-04-15 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flexibility_platform', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deliveryperiod',
            name='status',
            field=models.CharField(choices=[('started', 'STARTED'), ('gct', 'GCT'), ('waiting', 'WAITING'), ('ended', 'ENDED')], default='started', max_length=10),
        ),
    ]
