# Generated by Django 2.0.7 on 2020-04-27 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flexibility_platform', '0003_auto_20200421_1150'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemoperator',
            name='url',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
