# Generated by Django 2.0.7 on 2020-05-11 04:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('flexibility_platform', '0004_systemoperator_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='system_operator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='flexibility_platform.SystemOperator'),
        ),
    ]
