# Generated by Django 2.0.7 on 2020-09-29 08:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('flexibility_platform', '0005_product_system_operator'),
    ]

    operations = [
        migrations.CreateModel(
            name='AggregatorInformation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identification', models.TextField()),
                ('name', models.TextField()),
                ('contact', models.TextField()),
                ('fsp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='flexibility_platform.FlexibilityServiceProvider')),
            ],
        ),
    ]
