# Generated by Django 2.0.7 on 2020-10-26 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flexibility_platform', '0006_aggregatorinformation'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='direction',
            field=models.CharField(choices=[('+', 'Up'), ('-', 'Down')], default=1, max_length=5),
            preserve_default=False,
        ),
    ]
