# Generated by Django 2.0.7 on 2020-05-14 09:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('activation', '0008_auto_20200511_0134'),
        ('flexibility_platform', '0005_product_system_operator'),
    ]

    operations = [
        migrations.CreateModel(
            name='MeteringData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('energy', models.TextField()),
                ('metering_point_id', models.TextField()),
                ('start_of_delivery_period', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('fsp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='flexibility_platform.FlexibilityServiceProvider')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='flexibility_platform.Product')),
            ],
        ),
        migrations.CreateModel(
            name='RequestForMeteringData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meter_point_id', models.TextField()),
                ('start_of_delivery_period', models.DateTimeField()),
                ('fsp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='flexibility_platform.FlexibilityServiceProvider')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='flexibility_platform.Product')),
            ],
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('energy', models.TextField()),
                ('metering_point_id', models.TextField()),
                ('start_of_delivery_period', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('fsp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='flexibility_platform.FlexibilityServiceProvider')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='flexibility_platform.Product')),
            ],
        ),
        migrations.CreateModel(
            name='Verification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('metering_point_id', models.TextField()),
                ('result', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('flexibility_activation_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='activation.FlexibilityActivationOrder')),
                ('flexibility_activation_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='activation.FlexibilityActivationRequest')),
                ('flexibility_service_provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='flexibility_platform.FlexibilityServiceProvider')),
                ('system_operator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='flexibility_platform.SystemOperator')),
            ],
        ),
    ]
