<?xml version="1.0" encoding="UTF-8"?>
<!--
This file was generated by Altova MapForce 2021

YOU SHOULD NOT MODIFY THIS FILE, BECAUSE IT WILL BE
OVERWRITTEN WHEN YOU RE-RUN CODE GENERATION.

Refer to the Altova MapForce Documentation for further details.
http://www.altova.com/mapforce
-->
<xsl:stylesheet version="2.0" xmlns:xsl="http://www.w3.org/1999/XSL/Transform" xmlns:ns0="CIM/EuSysFlex/FlexibilityBid" xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:fn="http://www.w3.org/2005/xpath-functions" exclude-result-prefixes="ns0 xs fn">
	<xsl:output method="xml" encoding="UTF-8" byte-order-mark="no" indent="yes"/>
	<xsl:template match="/">
		<xsl:variable name="var1_FlexibilityBid_MarketDocument" as="node()?" select="ns0:FlexibilityBid_MarketDocument"/>
		<FlexibilityBid>
			<xsl:attribute name="xsi:noNamespaceSchemaLocation" namespace="http://www.w3.org/2001/XMLSchema-instance" select="'file:///C:/Users/d93057/Documents/OneDrive%20-%20EDF/Espace%20de%20travail/Projets%20europ%C3%A9ens/EUSysFlex/WP5/CIM%20Profiling/ActualFlexibilityBid.xsd'"/>
			<xsl:for-each select="$var1_FlexibilityBid_MarketDocument">
				<flexibility_service_provider>
					<xsl:sequence select="fn:string(Provider_MarketParticipant/mRID)"/>
				</flexibility_service_provider>
			</xsl:for-each>
			<xsl:for-each select="$var1_FlexibilityBid_MarketDocument/Bid_TimeSeries">
				<product_id>
					<xsl:sequence select="fn:string(product)"/>
				</product_id>
			</xsl:for-each>
			<xsl:for-each select="$var1_FlexibilityBid_MarketDocument/Bid_TimeSeries/Metering_MarketEvaluationPoint">
				<metering_point_id>
					<xsl:sequence select="fn:string(mRID)"/>
				</metering_point_id>
			</xsl:for-each>
			<xsl:for-each select="$var1_FlexibilityBid_MarketDocument/Bid_TimeSeries/Delivery_Period/Point">
				<power>
					<xsl:sequence select="xs:string(xs:decimal(fn:string(quantity)))"/>
				</power>
			</xsl:for-each>
			<xsl:for-each select="$var1_FlexibilityBid_MarketDocument/Bid_TimeSeries/Delivery_Period/Point">
				<price>
					<xsl:sequence select="xs:string(xs:decimal(fn:string(Price/amount)))"/>
				</price>
			</xsl:for-each>
			<xsl:for-each select="$var1_FlexibilityBid_MarketDocument/Bid_TimeSeries">
				<linking_of_bids>
					<xsl:sequence select="xs:string((fn:count(Linked_BidTimeSeries) &gt; xs:decimal('0')))"/>
				</linking_of_bids>
			</xsl:for-each>
			<xsl:for-each select="$var1_FlexibilityBid_MarketDocument">
				<localization_factor>
					<xsl:sequence select="fn:string(LocalizationFactor_Domain/mRID)"/>
				</localization_factor>
			</xsl:for-each>
			<xsl:for-each select="$var1_FlexibilityBid_MarketDocument/Bid_TimeSeries/Delivery_Period">
				<start_of_delivery>
					<xsl:sequence select="xs:string(xs:dateTime(fn:string(timeInterval/start)))"/>
				</start_of_delivery>
			</xsl:for-each>
		</FlexibilityBid>
	</xsl:template>
</xsl:stylesheet>
