# Generated by Django 2.0.7 on 2020-04-28 06:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bidding', '0009_auto_20200428_0637'),
        ('flexibility_platform', '0004_systemoperator_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='BiddingGridImpactAssessmentResult',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('result', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('bid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bidding.FlexibilityBid')),
                ('system_operator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='flexibility_platform.SystemOperator')),
            ],
        ),
    ]
