# Generated by Django 2.0.7 on 2020-03-31 05:08

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('flexibility_platform', '0001_initial'),
        ('activation', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FlexibilityActivationOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('forwarded_quantity', models.DecimalField(decimal_places=3, max_digits=10, validators=[django.core.validators.MinValueValidator(0.01)])),
                ('direction', models.CharField(choices=[('plus', 'Up'), ('moins', 'Down')], max_length=1)),
                ('localization_factor', models.TextField()),
                ('start_of_delivery', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('flexibility_service_provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='flexibility_platform.FlexibilityServiceProvider')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='flexibility_platform.Product')),
            ],
        ),
        migrations.CreateModel(
            name='Verification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('metering_point_id', models.TextField()),
                ('result', models.TextField()),
                ('flexibility_activation_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='activation.FlexibilityActivationOrder')),
                ('flexibility_activation_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='activation.FlexibilityActivationRequest')),
                ('flexibility_service_provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='flexibility_platform.FlexibilityServiceProvider')),
            ],
        ),
    ]
