# Generated by Django 2.0.7 on 2020-05-05 09:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('flexibility_platform', '0004_systemoperator_url'),
        ('activation', '0004_flexibilityactivationrequest_bid_affected'),
    ]

    operations = [
        migrations.CreateModel(
            name='FlexibilityActivationConfirmation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('confirmation', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('flexibility_service_provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='flexibility_platform.FlexibilityServiceProvider')),
            ],
        ),
    ]
