# Generated by Django 2.0.7 on 2020-05-10 16:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('activation', '0006_auto_20200505_1211'),
    ]

    operations = [
        migrations.AddField(
            model_name='flexibilityactivationorder',
            name='request',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='activation.FlexibilityActivationRequest'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='flexibilityactivationrequest',
            name='status',
            field=models.CharField(choices=[('treated', 'Activation order confirmed by all FSPs'), ('no_mol', 'No bids on the MOL'), ('waiting', 'Not processed yet')], default='waiting', max_length=10),
        ),
    ]
