# Generated by Django 2.0.7 on 2020-05-18 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activation', '0008_auto_20200511_0134'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='flexibilityactivationorder',
            name='request',
        ),
        migrations.AddField(
            model_name='flexibilityactivationrequest',
            name='flexibility_activation_order',
            field=models.ManyToManyField(to='activation.FlexibilityActivationOrder'),
        ),
    ]
