# Generated by Django 2.0.7 on 2020-05-18 12:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bidding', '0009_auto_20200428_0637'),
        ('activation', '0009_auto_20200518_1449'),
    ]

    operations = [
        migrations.AddField(
            model_name='flexibilityactivationorder',
            name='bid',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='bidding.FlexibilityBid'),
            preserve_default=False,
        ),
    ]
