# Generated by Django 2.0.7 on 2020-10-26 09:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('activation', '0010_flexibilityactivationorder_bid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='flexibilityactivationorder',
            name='direction',
        ),
        migrations.RemoveField(
            model_name='flexibilityactivationrequest',
            name='direction',
        ),
    ]
