# Generated by Django 2.0.7 on 2020-03-24 14:13

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('flexibility_platform', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CallForTenders',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_power_needed', models.DecimalField(decimal_places=3, max_digits=10, null=True)),
                ('direction', models.CharField(choices=[('plus', 'Up'), ('moins', 'Down')], max_length=5)),
                ('linking_of_bids', models.BooleanField()),
                ('localization_factor', models.TextField()),
                ('opening_date', models.DateTimeField()),
                ('closing_date', models.DateTimeField(blank=True, null=True)),
                ('start_service_date', models.DateTimeField()),
                ('end_service_date', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('open', 'OPEN - SUBMISSION OPEN'), ('close', 'OPEN - SUBMISSION CLOSED'), ('cancelled', 'CLOSED'), ('waiting', 'PENDING')], default='open', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='callfortendersproduct', to='flexibility_platform.Product')),
                ('system_operator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='flexibility_platform.SystemOperator')),
            ],
        ),
        migrations.CreateModel(
            name='FlexibilityBid',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=3, max_digits=10, validators=[django.core.validators.MinValueValidator(0.01)])),
                ('power', models.DecimalField(decimal_places=3, max_digits=10, validators=[django.core.validators.MinValueValidator(0.01)])),
                ('direction', models.CharField(choices=[('plus', 'Up'), ('moins', 'Down')], max_length=1)),
                ('linking_of_bids', models.BooleanField()),
                ('metering_point_id', models.TextField()),
                ('localization_factor', models.TextField()),
                ('start_of_delivery', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('flexibility_service_provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='flexibility_platform.FlexibilityServiceProvider')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='flexibility_platform.Product')),
            ],
        ),
        migrations.CreateModel(
            name='MeritOrderList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('list_json', models.TextField()),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='flexibility_platform.Product')),
                ('service_product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='flexibility_platform.DeliveryPeriod')),
            ],
        ),
    ]
