# Generated by Django 2.0.7 on 2020-03-26 14:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bidding', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='flexibilitybid',
            name='call_for_tenders',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='bidding.CallForTenders'),
            preserve_default=False,
        ),
    ]
