# Generated by Django 2.0.7 on 2020-03-26 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bidding', '0002_flexibilitybid_call_for_tenders'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='flexibilitybid',
            name='call_for_tenders',
        ),
        migrations.AddField(
            model_name='flexibilitybid',
            name='call_for_tenders',
            field=models.ManyToManyField(to='bidding.CallForTenders'),
        ),
    ]
