# Generated by Django 2.0.7 on 2020-03-31 04:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bidding', '0005_auto_20200331_0619'),
    ]

    operations = [
        migrations.AlterField(
            model_name='callfortenders',
            name='localization_factor',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='flexibilitybid',
            name='localization_factor',
            field=models.TextField(blank=True, null=True),
        ),
    ]
