# Generated by Django 2.0.7 on 2020-04-14 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bidding', '0006_auto_20200331_0622'),
    ]

    operations = [
        migrations.AlterField(
            model_name='callfortenders',
            name='direction',
            field=models.CharField(choices=[('+', 'Up'), ('-', 'Down')], max_length=5),
        ),
        migrations.AlterField(
            model_name='flexibilitybid',
            name='direction',
            field=models.CharField(choices=[('+', 'Up'), ('-', 'Down')], max_length=10),
        ),
    ]
