# Generated by Django 2.0.7 on 2020-04-28 04:34

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bidding', '0007_auto_20200414_1520'),
    ]

    operations = [
        migrations.AddField(
            model_name='flexibilitybid',
            name='included_in_mol',
            field=models.NullBooleanField(),
        ),
        migrations.AddField(
            model_name='flexibilitybid',
            name='power_constraint',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0.01)]),
        ),
    ]
