# Generated by Django 2.0.7 on 2020-04-28 04:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bidding', '0008_auto_20200428_0634'),
    ]

    operations = [
        migrations.RenameField(
            model_name='flexibilitybid',
            old_name='power_constraint',
            new_name='power_constraint_by_grid',
        ),
        migrations.RenameField(
            model_name='flexibilitybid',
            old_name='power',
            new_name='power_left_after_activation',
        ),
        migrations.RenameField(
            model_name='flexibilitybid',
            old_name='power_left',
            new_name='power_origin',
        ),
    ]
